version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - /home/will/data/ollama:/root/.ollama
    container_name: ollama
    pull_policy: if_not_present
    tty: true
    restart: always
    networks:
      - ollama-docker

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: if_not_present
    volumes:
      - /home/will/data/webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 13000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=123456'
      - 'HF_ENDPOINT=https://hf-mirror.com'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  java-app:
    image: bolingcavalry/ollam-tutorial:0.0.1-SNAPSHOT
    container_name: java-app
    pull_policy: if_not_present
    depends_on:
      - ollama
    ports:
      - 18080:8080
    environment:
      - 'SPRING_AI_OLlama_BASE_URL=http://ollama:11434'
      - 'SPRING_AI_OLlama_CHAT_OPTIONS_MODEL=qwen:1.8b'
      - 'SPRING_AI_OLlama_CHAT_OPTIONS_TEMPERATURE=0.7'
      - 'SPRING_MAIN_WEB_APPLICATION_TYPE=reactive'
    restart: always
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false