---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: indexer-tutorials
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        # 这是个自定义lable，指定了mysql的语言类型是c语言
        language: c
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: indexer-tutorials
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None